
language: node_js
node_js:
  - 10

branches:
  only:
    - master

cache:
  directories:
    - node_modules
    - public
    - .cache

before_script:
  - npm i -g gatsby-cli
  - npm i -g netlify-cli
  - yarn

script:
  - travis_wait 55 gatsby build

deploy:
  provider: script
  script: netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --prod --dir=public
  skip_cleanup: true
  on:
    branch: master
